# Why NumPy?

. Numpy is faster than the list. List takes up more space (binary representation)
. Numpy is faster to read due to less bytes of memory
. No type checking when iterating though objects
. Numpy utilizes contiguous memory

### Load in Numpy

In [1]:
import numpy as np

### The basics

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b)

[ 4 10 18]


In [3]:
# get Dimension
c = np.array([[1,2,3],[4,5,6]])
c.ndim

2

In [4]:
# get shape
c.shape

(2, 3)

In [5]:
# get type
c.dtype

dtype('int64')

In [6]:
# get size
c.itemsize

8

### Accessing /Changing specific elements, rows, columns, etc

In [7]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
# get specific element
print(a[1, 5])
print(a[0, -3]) # -ve index access

13
5


In [9]:
# get specific row
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [10]:
# get specific column
a[:, 5]

array([ 6, 13])

In [11]:
# getting a little more fancy [startindex:endindex:stepsize]
a[1, 1:6:2]

array([ 9, 11, 13])

In [12]:
a[:,2] = [11,22]
a

array([[ 1,  2, 11,  4,  5,  6,  7],
       [ 8,  9, 22, 11, 12, 13, 14]])

* 3-D array

In [13]:
b = np.array( [ 
        [ [1,2], [3,4] ], 
        [ [5,6], [7,8] ] 
    ])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
# get scecific element (work outside in) 
b[1,0,1]

6

In [15]:
# replace
b[:,1,:] = [ [-3,-4], [-7,-8] ]
b

array([[[ 1,  2],
        [-3, -4]],

       [[ 5,  6],
        [-7, -8]]])

### Initializing different types of arrays

In [16]:
# All 0s matrix
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# All 1s matrix
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [18]:
# Any other number
np.full((3,4), 11, dtype='float32') # dtype (optional)

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]], dtype=float32)

In [19]:
# Any other number (full_like)
np.full_like(b, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [20]:
# random decimal numbers
np.random.rand(4,2)

array([[0.2939808 , 0.75224828],
       [0.60132555, 0.10792365],
       [0.58876142, 0.2338347 ],
       [0.93170328, 0.48070533]])

In [21]:
# random int values
np.random.randint(7, size=(3,3))

array([[2, 1, 3],
       [6, 0, 4],
       [0, 2, 6]])

In [22]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# repeat a pattern
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [24]:
# fancy stuff with replacing
output = np.ones((5,5))
print(output)
r = np.zeros((3,3))
print(r)
r[1,1] = 9
output[1:4,1:4] = r
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###### Be careful while copying arrays!

In [25]:
a = np.array([1,2,3])
b = a.copy()
b[1]= 100
print(a)

[1 2 3]


### Mathematics

In [26]:
a = np.array([2,4,6,8])

# basic
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)

# sin/cos
np.sin(a)

[ 4  6  8 10]
[0 2 4 6]
[ 4  8 12 16]
[1. 2. 3. 4.]
[ 4 16 36 64]


array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825])

### Linear Algebra

In [27]:
a = np.ones((3,2))
b = np.full((2,3), 3)

np.matmul(a,b)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [28]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [29]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.min(a)

1

In [31]:
np.max(a)

6

In [32]:
np.sum(a, axis = 1)


array([ 6, 15])

### Reorganizing arrays

In [33]:
before = np.array([[1,2,3,4], [5,6,7,8]])
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
# Vertically stacking vectors
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack([a,b,a,b])

# horizontally
np.hstack([a,b,a,b])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous

###### Load data from file

In [35]:
filedata = np.genfromtxt('data.txt', delimiter= ',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

###### Boolean masking and advanced indexing

In [36]:
np.any( (filedata > 50) & (filedata < 100), axis = 0)

array([False, False, False, False, False,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])